# See https://github.com/helm/chart-testing#configuration
chart-dirs:
  - charts
#chart-repos:
#  - helm-charts-template=https://swade1987.github.io/helm-charts-template
check-version-increment: true
helm-extra-args: --timeout 600
target-branch: main
validate-chart-schema: true
validate-maintainers: false
validate-yaml: true
