{{- if .Values.application.externalSecrets.database }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: {{ $.Release.Name }}
    app.kubernetes.io/subsystem: {{ $.Values.application.subsystem | quote }}
    app.kubernetes.io/tenant: {{ $.Values.tenant.name | quote }}
    app.kubernetes.io/version: {{ $.Values.application.image.tag | quote }}
    app: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
spec:
  target:
    name: {{ .Release.Name }}-db-{{ .Release.Revision }}
  refreshInterval: 1h
  secretStoreRef:
    name: external-secret-opr-cluster-secret-store
    kind: ClusterSecretStore
  data:
    {{- with .Values.application.externalSecrets.database }}
    {{- range . }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .parameterStoreLocation | quote }}
    {{- end }}
    {{- end }}
{{- end }}
