{{- if .Values.application.externalSecrets.additional }}
{{- range .Values.application.externalSecrets.additional }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: {{ $.Release.Name }}
    app.kubernetes.io/subsystem: {{ $.Values.application.subsystem | quote }}
    app.kubernetes.io/tenant: {{ $.Values.tenant.name | quote }}
    app.kubernetes.io/version: {{ $.Values.application.image.tag | quote }}
    app: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: external-secret-opr-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ $.Release.Name }}-{{ .name }}-{{ $.Release.Revision }}
    {{- toYaml .target | nindent 4 }}
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .parameterStoreLocation }}
    {{- end }}
{{- end }}
{{- end }}
