{{- if .Values.application.image.semver }}
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: {{ $.Release.Name }}
    app.kubernetes.io/subsystem: {{ $.Values.application.subsystem | quote }}
    app.kubernetes.io/tenant: {{ $.Values.tenant.name | quote }}
    app.kubernetes.io/version: {{ $.Values.application.image.tag | quote }}
    app: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: k8s-releases-ksoc-v2
    namespace: flux-repos
  git:
    checkout:
      ref:
        branch: main
    push:
      branch: sbx-image-updates
    commit:
      messageTemplate: |
        Automatic image update from FluxCD: {{ "{{" }} range .Updated.Images {{ "}}" }}{{ "{{" }}println . {{ "}}" }}{{ "{{" }}end{{ "}}" }}
      author:
        email: engineering@algbra.com
        name: AlgbraEngineering
{{- end }}
