{{- if .Values.mongo.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: {{ $.Release.Name }}
    app.kubernetes.io/subsystem: {{ $.Values.application.subsystem | quote }}
    app.kubernetes.io/tenant: {{ $.Values.tenant.name | quote }}
    app.kubernetes.io/version: {{ $.Values.application.image.tag | quote }}
    app: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
spec:
  target:
    name: {{ .Release.Name }}-mongodb-ca-cert
    refreshInterval: 1h
    secretStoreRef:
      name: external-secret-opr-cluster-secret-store
      kind: ClusterSecretStore
    data:
      - secretKey: ca-cert
        remoteRef:
          key: /infrastructure/certmanager/selfsigned-ca/tlscrt
{{- end }}
