apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: {{ $.Release.Name }}
    app.kubernetes.io/subsystem: {{ $.Values.application.subsystem | quote }}
    app.kubernetes.io/tenant: {{ $.Values.tenant.name | quote }}
    app.kubernetes.io/version: {{ $.Values.application.image.tag | quote }}
    app: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
  {{- with .Values.application.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.application.service.ports.http }}
      targetPort: {{ .Values.application.service.ports.http }}
      protocol: TCP
    - name: tcp
      port: {{ .Values.application.service.ports.tcp }}
      targetPort: {{ .Values.application.service.ports.tcp }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
